#pragma once
#include "esphome/core/macros.h"
#define API_MAX_SEND_QUEUE 8
#define CONTROLLER_REGISTRY_MAX 1
#define ESPHOME_BOARD "esp32-s3"
#define ESPHOME_COMPONENT_COUNT 20
#define ESPHOME_ENTITY_LIGHT_COUNT 1
#define ESPHOME_ENTITY_SENSOR_COUNT 3
#define ESPHOME_LOGGER_TX_BUFFER_SIZE 512
#define ESPHOME_LOG_MAX_LISTENERS 1
#define ESPHOME_LOOP_TASK_STACK_SIZE 8192
#define ESPHOME_TASK_LOG_BUFFER_SIZE 768
#define ESPHOME_THREAD_MULTI_ATOMICS
#define ESPHOME_VARIANT "ESP32-S3"
#define MAX_API_CONNECTIONS 5
#define MDNS_SERVICE_COUNT 1
#define USE_API
#define USE_API_PLAINTEXT
#define USE_CAPTIVE_PORTAL
#define USE_CAPTIVE_PORTAL_GZIP
#define USE_CONTROLLER_REGISTRY
#define USE_DEBUG
#define USE_ENTITY_ICON
#define USE_ENTITY_UNIT_OF_MEASUREMENT
#define USE_ESP32_CRASH_HANDLER
#define USE_ESPHOME_TASK_LOG_BUFFER
#define USE_ESP_IDF_VERSION_CODE VERSION_CODE(5, 5, 5)
#define USE_LIGHT
#define USE_LIGHT_GAMMA_LUT
#define USE_LOGGER
#define USE_LOGGER_UART_SELECTION_USB_SERIAL_JTAG
#define USE_LOGGER_USB_CDC
#define USE_LOGGER_USB_SERIAL_JTAG
#define USE_LOG_LISTENERS
#define USE_MD5
#define USE_MDNS
#define USE_MICROPHONE
#define USE_MICRO_WAKE_WORD
#define USE_NATIVE_64BIT_TIME
#define USE_NETWORK
#define USE_NETWORK_IPV6 false
#define USE_OTA
#define USE_OTA_ROLLBACK
#define USE_OTA_STATE_LISTENER
#define USE_OTA_VERSION 2
#define USE_PREFERENCE_KEY_LOOKUP
#define USE_SAFE_MODE_BOOT_IS_GOOD_ON_SHUTDOWN
#define USE_SENSOR
#define USE_SHA256
#define USE_SOCKET_IMPL_BSD_SOCKETS
#define USE_VOICE_ASSISTANT
#define USE_WEBSERVER_OTA
#define USE_WIFI
#define USE_WIFI_AP
#define USE_WIFI_SCAN_RESULTS_LOCK
#define WEB_SERVER_DEFAULT_HEADERS_COUNT 1
